### ISSUE TITLE
Running from a local index.htm does not work

### ISSUE THREAD

**Issue by daladim** [rednetio/chord-display#15]
Thanks for this amazing software that helps me learn to read and play chords.

I'm trying to fiddle with tonaljs, and hence I was trying to run a local version. As you wrote in your readme, I downloaded and extracted your zip file and opened `index.htm` in Chrome 97 on macOS.

However, the scripts do not load, and I have a `Uncaught SyntaxError: Cannot use import statement outside a module` error in the console.
![Capture d’écran 2022-01-20 à 22 02 00](https://user-images.githubusercontent.com/6873361/150421678-4f70b1a0-699a-4c01-8920-27c79d182281.png)

Javascript is not my cup of tea, but a [stackoverflow answer](https://stackoverflow.com/a/58679392) suggested to add a `type="module"` in the javascript invocation. I did so, then I had CORS errors, which I finally managed to bypass, only to have even more errors about the server (but I'm using a local version!) that did not serve the JS with the correct MIME type.

Anyway, do you know how to run your webapp from a local version (so that I can finally fiddle with tonaljs)?
Safari renders the same page, and I obviously cannot try Firefox, which does not support webmidi

Thanks

**Comment by ArTiSTiX** [comment]
Hi @daladim !
I’m happy to know you tested my project. Are your running the built index.html ?
I kinda put this project on hold, mainly because of OBS not supporting MIDI, but I would be glad to help you run it as intended in the first place. I’ll check on your feedback asap, but the project is supposed to run even without node running (just the index in the dist directory should run).  It helped me a lot with learning chords, even if it still has some flaws. I have some time to work on it if you need.

Don’t hesitate to reply here if you need more help, I’ll be available in the next few weeks.

**Comment by daladim** [comment]
Thanks for your reply.

> Are your running the built index.html ?

I am using the index.html from [the link you've provided](https://github.com/rednetio/chord-display/archive/master.zip) in your Readme. That is, `archive/master.zip`, which I think is as if I had cloned the project (that's not a build artifact).
Also, I'm using static files lying on my disk, without node running nor serving anything (and I'd like to avoid running node if possible, the computer I have plugged on my MIDI keyboard is getting quite old and slow xD )

I'm not a web developer, but I have (just a few) notions about HTML and JS all the same, so I'll be glad to help you debug and/or fix this if I can :-) Please reach for me whenever you're ready to have a look!

Thanks

**Comment by ArTiSTiX** [comment]
Hello @daladim, sorry for the late response.

I checked the content of the zip, and everything works well on my end.

But ensure you extracted the zip somewhere, and open the **`index.html` located in the `dist` directory**.
The `index.html` in the root directory is not built, it is just a html template.
The `dist` directory contains the built project, it's the running version.

**Comment by daladim** [comment]
Oops, that was it. Opening `dist/index.html` works like a charm. This was clearly written in your Readme, but I read too quickly :-/

Thanks for your reply anyway!
I'm closing this issue (and I'll go back to tonaljs, now I have a playground to tweak it :D )
